image:
  name: autostats:latest # this image is created on gitlab server
  entrypoint: [""]

# image: python:3.7  # for local tests decomment this

stages:
  - tests
  


tests:
  stage: tests
  script:
    - echo "starting tests"
    - python3 -m pytest -s tests/main_pipeline/